# Generated by Django 3.2.16 on 2024-02-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellor.counsellor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
